import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  LogarithmicScale,
  RadialLinearScale,
  TimeScale,
  TimeSeriesScale,
  BarElement,
  LineElement,
  PointElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
  BarController,
  LineController,
  Filler,
  DoughnutController,
  PieController,
  ScatterController,
  BubbleController,
  PolarAreaController,
  RadarController,
} from 'chart.js'

// Register all Chart.js components
ChartJS.register(
  CategoryScale,
  LinearScale,
  LogarithmicScale,
  RadialLinearScale,
  TimeScale,
  TimeSeriesScale,
  BarElement,
  LineElement,
  PointElement,
  ArcElement,
  Title,
  Tooltip,
  Legend,
  BarController,
  LineController,
  Filler,
  DoughnutController,
  PieController,
  ScatterController,
  BubbleController,
  PolarAreaController,
  RadarController
)

export { ChartJS }